---
- name: Creating an EC2 Instance with Creating a VPC and Subnet Id
  hosts: localhost
  tasks:
    - name: Create a new VPC 
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ cidr_block }}"
        region: "{{ region }}"
      register: vpc
      
    - name: "Artifact the VPC vars"
      ansible.builtin.set_stats:
        data:
          vpc: "{{vpc}}"

    - name: Change the VPC the gateway is attached to
      amazon.aws.ec2_vpc_igw:
        internet_gateway_id: "igw-0c903b08033565411"
        vpc_id: "{{vpc.vpc.id}}"
        force_attach: true
        state: present
      register: igw

    - name: Create gateway route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        tags:
          Name: Gateway route table
        gateway_id: "igw-0c903b08033565411"
      register: gateway_route_table

#    - name: Change the VPC the gateway is attached to
#      amazon.aws.ec2_vpc_igw:
#        internet_gateway_id: "{{igw.gateway_id}}"
#        vpc_id: "{{vpc.vpc_id}}"
#        force_attach: true
#        state: present
#      register: igw
  
    
         
