---
- name: Creating an EC2 Instance with Creating a VPC and Subnet Id
  hosts: localhost
  tasks:
    - name: Create a new VPC 
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ cidr_block }}"
        region: "{{ region }}"
      register: vpc
      
    - name: "Artifact the VPC vars"
      ansible.builtin.set_stats:
        data:
          vpc: "{{vpc}}"

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
      register: igw
  
    
         
