name: Build app and create infraestructure

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://ec2-3-12-85-240.us-east-2.compute.amazonaws.com:8081/
        username: admin
        password: ${{ secrets.nexuspassword }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=com.example artifactId=app version=1.0.0
        assets: extension=jar
        filename: target/myapp_server-0.0.1-SNAPSHOT.jar

######
    - name: "Test AWX: Simple job template without waiting"
      uses: fitbeard/action-trigger-awx@v24.2.0
      with:
        controller_verify_ssl: false
        controller_host: ${{ secrets.CONTROLLER_HOST }}
        controller_oauth_token: ${{ secrets.CONTROLLER_OAUTH_TOKEN }}
        resource_type: workflow_job_template
        resource_name: aws-workflow-job-template
          
